Repository aai-institute/pyDVL, pull requests merged in 2022-11, with the labels that each got.

#181 Fix powerset sampling
  CHANGELOG.md
  src/pydvl/shapley/montecarlo.py
  src/pydvl/utils/numeric.py
  tests/utils/test_numeric.py
Labels: bug, cleanup

#186 Make pull request template link PR to issue
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: cleanup

#194 Owen sampling
  CHANGELOG.md
  README.md
  docs/10-getting-started.rst
  docs/20-install.rst
  docs/30-data-valuation.rst
  docs/conf.py
  docs/index.rst
  docs/pydvl.bib
  notebooks/influence_synthetic.ipynb
  notebooks/notebook_support.py
  notebooks/shapley_basic_spotify.ipynb
  notebooks/shapley_knn_flowers.ipynb
  notebooks/shapley_utility_learning.ipynb
  src/pydvl/reporting/plots.py
  src/pydvl/shapley/montecarlo.py
  src/pydvl/utils/__init__.py
  src/pydvl/utils/caching.py
  src/pydvl/utils/config.py
  src/pydvl/utils/dataset.py
  src/pydvl/utils/numeric.py
  src/pydvl/utils/parallel/actor.py
  src/pydvl/utils/parallel/backend.py
  src/pydvl/utils/parallel/map_reduce.py
  src/pydvl/utils/types.py
  src/pydvl/utils/utility.py
  src/pydvl/value/__init__.py
  src/pydvl/value/banzhaf/__init__.py
  src/pydvl/value/banzhaf/montecarlo.py
  src/pydvl/value/loo/__init__.py
  src/pydvl/value/loo/naive.py
  src/pydvl/value/shapley/__init__.py
  src/pydvl/value/shapley/actor.py
  src/pydvl/value/shapley/knn.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/naive.py
  tests/conftest.py
  tests/shapley/test_knn.py
  tests/shapley/test_montecarlo.py
  tests/shapley/test_naive.py
  tests/utils/test_caching.py
  tests/utils/test_numeric.py
  tests/utils/test_parallel.py
  tests/utils/test_utility.py
  tox.ini
Labels: documentation, enhancement, heavy task, cleanup

#199 Allow manual triggering of pypi releases
  .github/workflows/publish.yaml
Labels: CI
