Repository aai-institute/pyDVL, pull requests merged in 2022-10, with the labels that each got.

#150 Fixes
  README-dev.md
  README.md
Labels: documentation

#152 Fixes and improvements to package release to TestPyPI
  .github/workflows/tox.yaml
  tox.ini
Labels: CI, packaging

#155 Improve adding Notebooks to the Documentation
  .github/workflows/tox.yaml
  docs/_ext/copy_notebooks.py
  docs/conf.py
  tox.ini
Labels: documentation

#159 Fix preview release creation in CI
  .bumpversion.cfg
  .github/workflows/tox.yaml
  setup.py
  src/pydvl/__init__.py
  tox.ini
Labels: CI, packaging

#162 Add more badges to readme
  README.md
Labels: documentation

#170 Fix catching of ConnectionRefusedError in caching
  src/pydvl/utils/caching.py
  tests/utils/test_caching.py
Labels: bug

#176 Fix chunkification of data in MapReduceJob
  .github/workflows/publish.yaml
  .github/workflows/run-tests-workflow.yaml
  .github/workflows/tox.yaml
  CHANGELOG.md
  requirements-dev.txt
  src/pydvl/utils/parallel/map_reduce.py
  tests/utils/test_parallel.py
  tox.ini
Labels: bug

#161 Doc/fixes
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README-dev.md
  README.md
  build_scripts/update_docs.py
  docs/10-getting-started.rst
  docs/20-install.rst
  docs/30-data-valuation.rst
  docs/40-influence.rst
  docs/_ext/copy_notebooks.py
  docs/conf.py
  docs/examples/index.rst
  docs/getting-started.rst
  docs/index.rst
  docs/install.rst
  notebooks/data_utility_learning.ipynb
  notebooks/influence_synthetic.ipynb
  notebooks/influence_wine.ipynb
  notebooks/knn_shapley_flowers.ipynb
  notebooks/shapley_basic_spotify.ipynb
  notebooks/shapley_knn_flowers.ipynb
  notebooks/shapley_spotify.ipynb
  notebooks/shapley_utility_learning.ipynb
  pyproject.toml
  requirements-dev.txt
  src/pydvl/influence/linear.py
  src/pydvl/loo/naive.py
  src/pydvl/reporting/plots.py
  src/pydvl/shapley/__init__.py
  src/pydvl/shapley/actor.py
  src/pydvl/shapley/knn.py
  src/pydvl/shapley/montecarlo.py
  src/pydvl/shapley/naive.py
  src/pydvl/utils/caching.py
  src/pydvl/utils/config.py
  src/pydvl/utils/dataset.py
  src/pydvl/utils/numeric.py
  src/pydvl/utils/parallel/actor.py
  src/pydvl/utils/parallel/backend.py
  src/pydvl/utils/parallel/map_reduce.py
  src/pydvl/utils/plotting.py
  src/pydvl/utils/utility.py
  tests/conftest.py
  tests/influence/test_models.py
  tests/shapley/test_knn.py
  tests/shapley/test_montecarlo.py
  tests/shapley/test_naive.py
  tests/utils/test_caching.py
  tests/utils/test_numeric.py
  tests/utils/test_utility.py
  tox.ini
Labels: documentation
