Repository aai-institute/pyDVL, pull requests merged in 2022-12, with the labels that each got.

#208 Support python versions from 3.8 to 3.10
  .github/workflows/run-tests-workflow.yaml
  .github/workflows/tox.yaml
  CHANGELOG.md
  setup.py
  tox.ini
Labels: CI

#216 Doc improvements
  docs/40-influence.rst
  docs/conf.py
  docs/index.rst
  src/pydvl/influence/__init__.py
  src/pydvl/utils/config.py
  src/pydvl/utils/numeric.py
  src/pydvl/utils/utility.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/naive.py
  tox.ini
Labels: documentation

#214 ValuationResult
  CHANGELOG.md
  docs/30-data-valuation.rst
  notebooks/shapley_basic_spotify.ipynb
  notebooks/shapley_knn_flowers.ipynb
  notebooks/shapley_utility_learning.ipynb
  src/pydvl/utils/types.py
  src/pydvl/value/__init__.py
  src/pydvl/value/loo/naive.py
  src/pydvl/value/results.py
  src/pydvl/value/shapley/__init__.py
  src/pydvl/value/shapley/actor.py
  src/pydvl/value/shapley/knn.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/naive.py
  tests/conftest.py
  tests/influence/__init__.py
  tests/shapley/test_knn.py
  tests/shapley/test_montecarlo.py
  tests/shapley/test_naive.py
  tests/test_results.py
  tests/utils/test_caching.py
Labels: enhancement

#195 Cnn influence example
  .gitignore
  CHANGELOG.md
  notebooks/influence_imagenet.ipynb
  notebooks/influence_synthetic.ipynb
  notebooks/influence_wine.ipynb
  notebooks/notebook_support.py
  requirements-dev.txt
  requirements-notebooks.txt
  requirements.txt
  src/pydvl/influence/conjugate_gradient.py
  src/pydvl/influence/frameworks/torch_differentiable.py
  src/pydvl/influence/general.py
  src/pydvl/influence/model_wrappers/__init__.py
  src/pydvl/influence/model_wrappers/torch_wrappers.py
  src/pydvl/reporting/plots.py
  src/pydvl/utils/dataset.py
  tests/influence/test_influences.py
  tox.ini
Labels: documentation, enhancement
