Repository aai-institute/pyDVL, pull requests merged in 2023-09, with the labels that each got.

#420 Fix publish action and release to testpypi
  .github/workflows/main.yaml
  .github/workflows/publish.yaml
  CONTRIBUTING.md
  requirements-dev.txt
Labels: CI

#426 Implementation of Kwon and Zou Data-OOB: Out-of-bag Estimate as a Sim…
  docs/assets/pydvl.bib
  mkdocs.yml
  notebooks/data_oob.ipynb
  src/pydvl/value/__init__.py
  src/pydvl/value/oob/__init__.py
  src/pydvl/value/oob/oob.py
Labels: new-method

#428 Batch (parallelized) calculations of beta Shapley
  CHANGELOG.md
  src/pydvl/utils/dataset.py
  src/pydvl/utils/types.py
  src/pydvl/value/oob/oob.py
  src/pydvl/value/result.py
  src/pydvl/value/sampler.py
  src/pydvl/value/semivalues.py
  src/pydvl/value/shapley/montecarlo.py
  tests/value/shapley/test_montecarlo.py
  tests/value/test_semivalues.py
  tests/value/utils.py
Labels: enhancement, light task

#432 A bit of cleanup
  .readthedocs.yaml
  CONTRIBUTING.md
  README.md
  apt-cache/.gitignore
  build_scripts/copy_changelog.py
  build_scripts/copy_notebooks.py
  docs/value/index.md
  notebooks/support/torch.py
  requirements-docs.txt
  src/pydvl/utils/caching.py
  src/pydvl/utils/numeric.py
  src/pydvl/utils/score.py
  src/pydvl/utils/types.py
  src/pydvl/utils/utility.py
  src/pydvl/value/result.py
  src/pydvl/value/semivalues.py
  src/pydvl/value/shapley/common.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/truncated.py
  src/pydvl/value/stopping.py
  tests/influence/test_torch_differentiable.py
  tests/utils/test_numeric.py
  tests/utils/test_parallel.py
  tests/value/__init__.py
Labels: cleanup

#439 Improve antithetic sampling
  CHANGELOG.md
  docs/assets/pydvl.bib
  src/pydvl/value/sampler.py
  tests/value/test_semivalues.py
Labels: bug, enhancement
