Repository aai-institute/pyDVL, pull requests merged in 2023-10, with the labels that each got.

#443 Fix data_names in ValuationResult.zeros()
  CHANGELOG.md
  src/pydvl/reporting/plots.py
  src/pydvl/value/result.py
Labels: bug

#444 Fix pytest xdist
  .github/workflows/run-tests-workflow.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  requirements-dev.txt
  tests/conftest.py
  tests/docker-compose.yml
  tests/utils/test_caching.py
  tox.ini
Labels: bug, testing

#338 Implement class wise shapley
  CHANGELOG.md
  README.md
  docs/api/pydvl/value/shapley/classwise/img/classwise-shapley-discounted-utility-function.svg
  docs/value/classwise-shapley.md
  docs/value/img/classwise-shapley-density.svg
  docs/value/img/classwise-shapley-discounted-utility-function.svg
  docs/value/img/classwise-shapley-metric-auc-cv.svg
  docs/value/img/classwise-shapley-metric-auc-mean.svg
  docs/value/img/classwise-shapley-metric-wad-cv.svg
  docs/value/img/classwise-shapley-metric-wad-mean.svg
  docs/value/img/classwise-shapley-roc-auc-logistic-regression.svg
  docs/value/img/classwise-shapley-weighted-accuracy-drop-logistic-regression-to-logistic-regression.svg
  docs/value/img/classwise-shapley-weighted-accuracy-drop-logistic-regression-to-mlp.svg
  docs/value/notation.md
  docs/value/shapley.md
  docs_includes/abbreviations.md
  mkdocs.yml
  src/pydvl/utils/numeric.py
  src/pydvl/utils/score.py
  src/pydvl/value/result.py
  src/pydvl/value/semivalues.py
  src/pydvl/value/shapley/__init__.py
  src/pydvl/value/shapley/classwise.py
  src/pydvl/value/shapley/gt.py
  src/pydvl/value/shapley/truncated.py
  src/pydvl/value/stopping.py
  tests/utils/test_numeric.py
  tests/value/shapley/test_classwise.py
  tests/value/test_stopping.py
Labels: enhancement, new-method, paper reproduction
