Repository aai-institute/pyDVL, pull requests merged in 2023-01, with the labels that each got.

#239 Fix ray initialization
  CHANGELOG.md
  src/pydvl/utils/parallel/backend.py
  tests/utils/conftest.py
Labels: bug

#240 Feature/group testing
  CHANGELOG.md
  README.md
  docs/30-data-valuation.rst
  docs/pydvl.bib
  notebooks/influence_synthetic.ipynb
  notebooks/least_core_basic.ipynb
  notebooks/shapley_basic_spotify.ipynb
  notebooks/shapley_utility_learning.ipynb
  requirements.txt
  src/pydvl/utils/numeric.py
  src/pydvl/utils/utility.py
  src/pydvl/value/least_core/montecarlo.py
  src/pydvl/value/results.py
  src/pydvl/value/shapley/__init__.py
  src/pydvl/value/shapley/actor.py
  src/pydvl/value/shapley/gt.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/naive.py
  tests/utils/test_numeric.py
  tests/value/conftest.py
  tests/value/least_core/conftest.py
  tests/value/least_core/test_montecarlo.py
  tests/value/loo/conftest.py
  tests/value/shapley/test_gt.py
  tests/value/shapley/test_montecarlo.py
Labels: new-method

#238 Fix/cleanup
  CONTRIBUTING.md
  build_scripts/update_docs.py
  docs/10-getting-started.rst
  docs/20-install.rst
  docs/30-data-valuation.rst
  docs/conf.py
  docs/pydvl.bib
  src/pydvl/utils/utility.py
  src/pydvl/value/banzhaf/__init__.py
  src/pydvl/value/banzhaf/montecarlo.py
  src/pydvl/value/least_core/_common.py
  src/pydvl/value/least_core/montecarlo.py
  src/pydvl/value/least_core/naive.py
  src/pydvl/value/shapley/knn.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/naive.py
  tests/value/conftest.py
Labels: documentation, cleanup

#247 Fix using remote ray actor with external cluster
  CHANGELOG.md
  src/pydvl/utils/parallel/actor.py
  src/pydvl/utils/parallel/backend.py
  src/pydvl/utils/utility.py
  src/pydvl/value/shapley/actor.py
  src/pydvl/value/shapley/montecarlo.py
  tests/conftest.py
  tests/utils/conftest.py
  tests/utils/test_parallel.py
  tests/utils/test_utility.py
  tests/value/conftest.py
  tests/value/least_core/conftest.py
  tests/value/least_core/test_montecarlo.py
  tests/value/least_core/test_naive.py
  tests/value/shapley/test_gt.py
  tests/value/shapley/test_montecarlo.py
Labels: bug

#248 TMCS stopping, 1 of ...
  CHANGELOG.md
  requirements-dev.txt
  src/pydvl/utils/__init__.py
  src/pydvl/utils/caching.py
  src/pydvl/utils/numeric.py
  src/pydvl/utils/status.py
  src/pydvl/value/least_core/montecarlo.py
  src/pydvl/value/least_core/naive.py
  src/pydvl/value/loo/naive.py
  src/pydvl/value/results.py
  src/pydvl/value/shapley/__init__.py
  src/pydvl/value/shapley/actor.py
  src/pydvl/value/shapley/gt.py
  src/pydvl/value/shapley/knn.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/naive.py
  src/pydvl/value/shapley/types.py
  tests/test_results.py
  tests/utils/test_caching.py
  tests/utils/test_numeric.py
  tests/utils/test_status.py
  tests/value/conftest.py
  tests/value/least_core/conftest.py
  tests/value/loo/conftest.py
  tests/value/shapley/test_gt.py
Labels: enhancement
