Repository aai-institute/pyDVL, pull requests merged in 2023-08, with the labels that each got.

#393 setting device to lanzcos_low_rank_hessian_approx
  src/pydvl/influence/frameworks/torch_differentiable.py
  tests/influence/test_influences.py
Labels: bug

#402 Test docs deploy and improve ci
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/deploy-docs/action.yml
  .github/actions/python/action.yml
  .github/workflows/publish.yaml
  .github/workflows/run-tests-workflow.yaml
  .github/workflows/tox.yaml
  CONTRIBUTING.md
  build_scripts/copy_changelog.py
  build_scripts/copy_notebooks.py
  requirements-dev.txt
  tox.ini
Labels: CI

#404 Improve data valuation docs and general navigation
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  build_scripts/generate_api_docs.py
  docs/10-getting-started.md
  docs/20-install.md
  docs/30-data-valuation.md
  docs/assets/pydvl.bib
  docs/css/extra.css
  docs/examples/index.md
  docs/getting-started/first-steps.md
  docs/getting-started/installation.md
  docs/index.md
  docs/influence/index.md
  docs/overrides/partials/copyright.html
  docs/value/img/mclc-best-removal-10k-natural.svg
  docs/value/img/mclc-worst-removal-10k-natural.svg
  docs/value/index.md
  docs/value/notation.md
  docs/value/semi-values.md
  docs/value/shapley.md
  docs/value/the-core.md
  docs_includes/abbreviations.md
  mkdocs.yml
  notebooks/shapley_basic_spotify.ipynb
  notebooks/shapley_knn_flowers.ipynb
  notebooks/shapley_utility_learning.ipynb
  requirements-docs.txt
  src/pydvl/utils/caching.py
  src/pydvl/utils/dataset.py
  src/pydvl/utils/numeric.py
  src/pydvl/utils/parallel/backend.py
  src/pydvl/utils/parallel/futures/__init__.py
  src/pydvl/utils/parallel/map_reduce.py
  src/pydvl/utils/progress.py
  src/pydvl/utils/utility.py
  src/pydvl/value/result.py
  src/pydvl/value/sampler.py
  src/pydvl/value/semivalues.py
  src/pydvl/value/shapley/__init__.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/owen.py
  src/pydvl/value/shapley/truncated.py
  src/pydvl/value/stopping.py
Labels: documentation

#408 Make ray an optional dependency
  CHANGELOG.md
  docs/conf.py
  requirements.txt
  setup.py
  src/pydvl/utils/parallel/__init__.py
  src/pydvl/utils/parallel/backend.py
  src/pydvl/utils/parallel/backends/__init__.py
  src/pydvl/utils/parallel/backends/joblib.py
  src/pydvl/utils/parallel/backends/ray.py
  src/pydvl/utils/parallel/futures/__init__.py
  src/pydvl/utils/parallel/futures/ray.py
  src/pydvl/value/shapley/montecarlo.py
  tests/conftest.py
  tests/utils/conftest.py
  tests/utils/test_parallel.py
  tests/value/conftest.py
Labels: packaging

#414 Small docs fixes
  .github/workflows/tox.yaml
  mkdocs.yml
  src/pydvl/influence/torch/torch_differentiable.py
  src/pydvl/influence/torch/util.py
  src/pydvl/influence/twice_differentiable.py
  src/pydvl/reporting/plots.py
  src/pydvl/utils/caching.py
  src/pydvl/utils/dataset.py
  src/pydvl/utils/parallel/futures/ray.py
  src/pydvl/utils/utility.py
Labels: documentation
