Repository aai-institute/pyDVL, pull requests merged in 2023-03, with the labels that each got.

#293 Hide parallel backend in tmcs main function
  src/pydvl/value/shapley/actor.py
  src/pydvl/value/shapley/truncated.py
Labels: cleanup

#290 Cosmetic changes to `Dataset`
  src/pydvl/utils/dataset.py
Labels: cleanup

#284 Refactor/nicer imports
  CHANGELOG.md
  README.md
  docs/conf.py
  notebooks/notebook_support.py
  notebooks/shapley_basic_spotify.ipynb
  notebooks/shapley_knn_flowers.ipynb
  notebooks/shapley_utility_learning.ipynb
  requirements.txt
  src/pydvl/reporting/plots.py
  src/pydvl/value/__init__.py
  src/pydvl/value/result.py
  src/pydvl/value/shapley/__init__.py
  src/pydvl/value/shapley/common.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/shapley/owen.py
  src/pydvl/value/stopping.py
Labels: bug, documentation, cleanup

#300 Fix StandardError stopping criterion
  CHANGELOG.md
  README.md
  notebooks/least_core_basic.ipynb
  notebooks/shapley_basic_spotify.ipynb
  src/pydvl/reporting/plots.py
  src/pydvl/utils/dataset.py
  src/pydvl/value/shapley/truncated.py
  src/pydvl/value/stopping.py
  tests/value/test_stopping.py
Labels: bug

#233 Remove unpackable decorator, use asdict()
  CHANGELOG.md
  requirements-dev.txt
  src/pydvl/utils/caching.py
  src/pydvl/utils/config.py
  src/pydvl/utils/types.py
  src/pydvl/utils/utility.py
  tests/conftest.py
Labels: cleanup

#305 Add burn-in param to AbsoluteStandardError
  CHANGELOG.md
  src/pydvl/value/stopping.py
  tests/value/test_stopping.py
Labels: bug

#307 Close #280: Add py.typed
  CHANGELOG.md
  setup.py
  src/pydvl/py.typed
Labels: packaging

#319 Semi-values and samplers
  CHANGELOG.md
  README.md
  docs/30-data-valuation.rst
  docs/conf.py
  src/pydvl/influence/conjugate_gradient.py
  src/pydvl/utils/numeric.py
  src/pydvl/value/__init__.py
  src/pydvl/value/sampler.py
  src/pydvl/value/semivalues.py
  src/pydvl/value/shapley/montecarlo.py
  src/pydvl/value/stopping.py
  tests/value/conftest.py
  tests/value/test_sampler.py
  tests/value/test_semivalues.py
  tox.ini
Labels: enhancement

#326 Remove bogus __iter__ method.
  src/pydvl/utils/dataset.py
Labels: cleanup
