Repository aai-institute/pyDVL, pull requests merged in 2024-04, with the labels that each got.

#550 Fix notebook tests
  .github/workflows/main.yaml
  .github/workflows/run-notebook-tests-workflow.yaml
  .notebook_test_durations
  notebooks/influence_sentiment_analysis.ipynb
  notebooks/influence_wine.ipynb
  notebooks/least_core_basic.ipynb
  requirements-dev.txt
  requirements-notebooks.txt
  tox.ini
Labels: bug, CI

#557 Add section to contributing guide about adding notes for new features…
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#520 MSR method for Banzhaf
  .notebook_test_durations
  CHANGELOG.md
  docs/assets/pydvl.bib
  docs/examples/img/msr_banzhaf_digits.png
  docs/examples/index.md
  docs/getting-started/glossary.md
  docs/value/semi-values.md
  docs_includes/abbreviations.md
  mkdocs.yml
  notebooks/least_core_basic.ipynb
  notebooks/msr_banzhaf_digits.ipynb
  notebooks/support/banzhaf.py
  src/pydvl/reporting/plots.py
  src/pydvl/value/result.py
  src/pydvl/value/sampler.py
  src/pydvl/value/semivalues.py
  src/pydvl/value/shapley/common.py
  src/pydvl/value/stopping.py
  tests/value/test_sampler.py
  tests/value/test_semivalues.py
  tests/value/test_stopping.py
  tox.ini
Labels: new-method
